# ~/.zshrc

[[ -d ~/.zfunc ]] && FPATH+=~/.zfunc

autoload -Uz compinit colors zcalc
compinit -d
colors

export PATH=$HOME/bin:$HOME/.cargo/bin:/usr/local/bin:$PATH

export EDITOR=/usr/bin/nvim

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

setprompt() {
  setopt prompt_subst

  p_host='%F{yellow}%M%f'

  PS1=${(j::Q)${(Z:Cn:):-$'
    %F{cyan}[%f
    %F{green}%D{%Y.%m.%d/%H:%M:%S}%f
    %F{cyan}][%f
    %(!.%F{red}%n%f.%F{green}%n%f)
    %F{cyan}@%f
    %F{cyan}]
    " "%(?.%F{green}%?%f.%F{red}%?%f)
    " "%f%F{blue}%~%f%F{cyan}
    "\n"
    %(!.%F{red}%#%f.%F{green}%#%f)
    " "
  '}}

  PS2=$'%_>'
}

setprompt

## Alias section

# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# json fancy format tool
alias jsf="python -mjson.tool"

_LOCAL_SSH_AUTH_SOCK="$HOME/.ssh/ssh_auth_socket"

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    # If ssh-agent process doesn't exists - spin it up
    rm -rf "${_LOCAL_SSH_AUTH_SOCK}"
    ssh-agent -a "${_LOCAL_SSH_AUTH_SOCK}" > ~/.ssh/agent_start.sh
    eval "$(<~/.ssh/agent_start.sh)" > /dev/null
else
    if [[ -z ${SSH_AUTH_SOCK} ]]; then
      SSH_AUTH_SOCK=$_LOCAL_SSH_AUTH_SOCK
      export SSH_AUTH_SOCK
    else
      if [[ ${SSH_AUTH_SOCK} != ${_LOCAL_SSH_AUTH_SOCK} ]]; then
        rm -rf $_LOCAL_SSH_AUTH_SOCK
        ln -s $SSH_AUTH_SOCK $_LOCAL_SSH_AUTH_SOCK
      fi
    fi
fi

## History Configuration

HISTSIZE=100000              # How many lines of history to keep in memory
HISTFILE=~/.zsh_history     # Where to save history to disk
SAVEHIST=5000               # Number of history entries to save to disk
HISTDUP=erase               # Erase duplicates in the history file
WORDCHARS=${WORDCHARS//\/[&.;]}     # Don't consider certain characters part of the word

## Options section
setopt    appendhistory     # Append history to the history file (no overwriting)
setopt    sharehistory      # Share history across terminals
setopt    incappendhistory  # Immediately append to the history file, not just when a term is killed
setopt    numericglobsort   # Sort filenames numerically when it makes sense
setopt    nobeep            # No beep

## Keybindings section
bindkey -e
bindkey '^[[7~' beginning-of-line                               # Home key
bindkey '^[[H' beginning-of-line                                # Home key
if [[ "${terminfo[khome]}" != "" ]]; then
  bindkey "${terminfo[khome]}" beginning-of-line                # [Home] - Go to beginning of line
fi
bindkey '^[[8~' end-of-line                                     # End key
bindkey '^[[F' end-of-line                                     # End key
if [[ "${terminfo[kend]}" != "" ]]; then
  bindkey "${terminfo[kend]}" end-of-line                       # [End] - Go to end of line
fi
bindkey '^[[2~' overwrite-mode                                  # Insert key
bindkey '^[[3~' delete-char                                     # Delete key
bindkey '^[[C'  forward-char                                    # Right key
bindkey '^[[D'  backward-char                                   # Left key
bindkey '^[[5~' history-beginning-search-backward               # Page up key
bindkey '^[[6~' history-beginning-search-forward                # Page down key

# Navigate words with ctrl+arrow keys
bindkey '^[Oc' forward-word                                     #
bindkey '^[Od' backward-word                                    #
bindkey '^[[1;5D' backward-word                                 #
bindkey '^[[1;5C' forward-word                                  #
bindkey '^H' backward-kill-word                                 # delete previous word with ctrl+backspace
bindkey '^[[Z' undo                                             # Shift+tab undo last action

plugins=(git ssh-agent)

[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
# #source /usr/share/nvm/init-nvm.sh
# #export PATH=$PATH:~/.yarn/bin
