#!/usr/bin/env bash

set -x -e

pacman -Suy \
  adobe-source-code-pro-fonts \
  adobe-source-han-sans-cn-fonts \
  adobe-source-han-sans-tw-fonts \
  alacritty \
  alsa-utils \
  arandr \
  aspell \
  aspell-en \
  bash \
  binutils \
  chromium \
  coreutils \
  curl \
  db \
  dmenu \
  dunst \
  firefox \
  fzf \
  git \
  gzip \
  i3-wm \
  i3lock \
  i3status \
  imagemagick \
  inkscape \
  iotop \
  iptables \
  less \
  linux \
  linux-api-headers \
  linux-firmware \
  lz4 \
  maim \
  make \
  neovim \
  network-manager-applet \
  networkmanager \
  networkmanager-openconnect \
  networkmanager-openvpn \
  nm-connection-editor \
  nodejs \
  noto-fonts-emoji \
  openssh \
  openssl \
  openvpn \
  pandoc \
  patch \
  pulseaudio \
  pulsemixer \
  python \
  readline \
  redshift \
  ripgrep \
  rofi \
  rofimoji \
  rsync \
  rtorrent \
  rustup \
  sed \
  startup-notification \
  sudo \
  sxiv \
  systemd \
  tar \
  terminus-font \
  terminus-font-otb \
  tmux \
  tree \
  ttf-font-awesome \
  ttf-inconsolata \
  ttf-liberation \
  unrar \
  unzip \
  usbutils \
  util-linux \
  vlc \
  which \
  wpa_supplicant \
  xdg-utils \
  xdotool \
  xkeyboard-config \
  xorg-docs \
  xorg-font-util \
  xorg-fonts-100dpi \
  xorg-fonts-75dpi \
  xorg-fonts-alias-100dpi \
  xorg-fonts-alias-75dpi \
  xorg-fonts-encodings \
  xorg-mkfontscale \
  xorg-server \
  xorg-setxkbmap \
  xorg-util-macros \
  xorg-xauth \
  xorg-xev \
  xorg-xinit \
  xorg-xinput \
  xorg-xkbutils \
  xorg-xkill \
  xorg-xmodmap \
  xorg-xset \
  xorgproto \
  xsel \
  yarn \
  zathura \
  zathura-pdf-mupdf \
  zsh \

